# Generated by Django 4.0.1 on 2022-02-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_images_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='description_uz',
            field=models.TextField(null=True),
        ),
    ]
