# Generated by Django 4.0.1 on 2022-02-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_faq_answer_en_faq_answer_ru_faq_answer_uz_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactmessage',
            name='status',
            field=models.CharField(choices=[('New', 'Yangi'), ('Read', "O'qilgan"), ('Closed', 'Yopilgan')], default='New', max_length=15),
        ),
    ]
