# Generated by Django 4.0.1 on 2022-02-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_slider_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='informations',
            name='locatsion',
            field=models.CharField(default=1, max_length=300),
            preserve_default=False,
        ),
    ]
