# Generated by Django 4.0.1 on 2022-02-10 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_informations_locatsion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='informations',
            old_name='locatsion',
            new_name='location',
        ),
    ]
