# Generated by Django 4.0.1 on 2022-02-04 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='quantity',
            new_name='amount',
        ),
    ]
