# Generated by Django 4.0.1 on 2022-02-04 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_rename_quantity_order_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='amount',
        ),
    ]
